locale: "en-US"
site_theme: "default"

title: "Maria Zimmermann"
title_separator: "-"
name: "Maria Zimmermann"
description: "Cognitive neuroscience of sign language, communication, and brain plasticity"

url: "https://maria-zimmermann.com"
baseurl: ""
repository: "MariaZofiaZimmermann/mariazofiazimmermann.github.io"

author:
  name: "Maria Zimmermann"
  bio: "Cognitive neuroscientist interested in how experience shapes the brain, with a current focus on meaning in sign and speech—from words and gestures to stories."
  avatar: "profile.png"
  location: "Poland"
  employer: "University of Warsaw"
  email: "maria.zimmermann@psych.uw.edu.pl"
  googlescholar: "https://scholar.google.pl/citations?user=GTTLxWcAAAAJ&hl=en&oi=sra"
 

publication_category:
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:

analytics:
  provider: false

atom_feed:
  hide: true

include:
  - _pages
  - files

collections:
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Europe/Warsaw

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
